name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: second_test
        type: choice
        options:
          - test_smoke_buy_sofa
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6
      - name: setup Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.12"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: test_smoke_buy_sofa
        if: "github.event.inputs.deployment_target == 'test_smoke_buy_sofa'"
        run: pytest tests/test_smoke_buy.py::test_smoke_buy_sofa
